### ISSUE TITLE
I have updated the rejective sampling

### ISSUE THREAD

**Issue by wangbingnan136** [VHRanger/CSRGraph#13]
https://github.com/wangbingnan136/CSRGraph

hello,I have updated the rejective sampling according to https://github.com/louisabraham/fastnode2vec,
can I merge to your great program?

![image](https://user-images.githubusercontent.com/42114835/125423351-91563bcf-8b00-414a-b440-caecd330b2d3.png)

**Comment by VHRanger** [comment]
Merged
