### ISSUE TITLE
NetworkX MultiGraph

### ISSUE THREAD

**Issue by shash42** [VHRanger/CSRGraph#15]
CSRGraph seems to be applicable to only networkx Graph and Digraph classes. Is there a way to make MultiGraphs work?

**Comment by VHRanger** [comment]
I don't think there's anything technically forbidding it if it's just self-loops and parallel edges to multigraphs.

I'd encourage you to try it, and log an issue if you run into technical issues.

I've been lagging on development for this package but it's going to be used in projects of mine this month and this fall, so it will see more development, especially on the graph side.

**Comment by shash42** [comment]
Right. It does seem to work alright, I just thought I'd make sure considering the csrgraph() call checks only if it's an instance of Graph and DiGraph explicitly, and not MultiGraph

**Comment by VHRanger** [comment]
Thanks, keep using it and please raise an issue if you run into something
